# -*- mode: python ; coding: utf-8 -*-
# client.spec - Full PyInstaller spec for complex client.py

import os
import sys
from PyInstaller.building.api import COLLECT, EXE, PYZ
from PyInstaller.building.build_main import Analysis
from PyInstaller.building.toc_conversion import DependencyProcessor
from PyInstaller.depend.utils import _resolveCtypesImports
import PyInstaller.config

# =============================================================================
# CONFIGURATION
# =============================================================================

block_cipher = None

# Platform-specific adjustments
is_windows = sys.platform == 'win32'
is_linux = sys.platform.startswith('linux')
is_macos = sys.platform == 'darwin'

# =============================================================================
# ANALYSIS - Main analysis for all imports
# =============================================================================

# Additional search paths
additional_paths = []

# Add common paths where dependencies might be
common_paths = [
    os.path.join(os.path.dirname(sys.executable), 'Lib', 'site-packages'),
    os.path.join(sys.exec_prefix, 'Lib', 'site-packages'),
    os.path.expanduser('~/.local/lib/python{}.{}/site-packages'.format(
        sys.version_info.major, sys.version_info.minor))
]

for path in common_paths:
    if os.path.exists(path):
        additional_paths.append(path)

# Main analysis
a = Analysis(
    ['client.py'],  # Your main script
    pathex=additional_paths,
    binaries=[],
    datas=[],
    hiddenimports=[
        # =========================================================================
        # CORE & WEB DEPENDENCIES
        # =========================================================================
        'socketio',
        'socketio.client',
        'socketio.asyncio_client',
        'socketio.async_client',
        'engineio',
        'engineio.async_drivers',
        'engineio.async_socket',
        'flask',
        'flask_cors',
        'flask_socketio',
        'werkzeug',
        'werkzeug.middleware',
        
        # Eventlet
        'eventlet',
        'eventlet.green',
        'eventlet.greenio',
        'eventlet.green.ssl',
        'eventlet.green.socket',
        'eventlet.green.select',
        'eventlet.green.threading',
        'eventlet.green.time',
        'eventlet.green.subprocess',
        'eventlet.wsgi',
        
        # Async/HTTP
        'aiohttp',
        'aiohttp.client',
        'aiohttp.client_reqrep',
        'aiohttp.connector',
        'aiohttp.helpers',
        'aiohttp.http',
        'aiohttp.http_parser',
        'aiohttp.http_writer',
        'aiohttp.multipart',
        'aiohttp.payload',
        'aiohttp.resolver',
        'aiohttp.signals',
        'aiohttp.streams',
        'aiohttp.tracing',
        'aiohttp.web',
        'aiohttp.web_app',
        'aiohttp.web_exceptions',
        'aiohttp.web_fileresponse',
        'aiohttp.web_log',
        'aiohttp.web_middlewares',
        'aiohttp.web_request',
        'aiohttp.web_response',
        'aiohttp.web_routedef',
        'aiohttp.web_runner',
        'aiohttp.web_server',
        'aiohttp.web_urldispatcher',
        'aiohttp.web_ws',
        'aiofiles',
        'aiofiles.threadpool',
        'aiofiles.os',
        'aiofiles.base',
        'asyncio',
        
        # WebSocket
        'websockets',
        'websockets.connection',
        'websockets.exceptions',
        'websockets.extensions',
        'websockets.frames',
        'websockets.headers',
        'websockets.http',
        'websockets.legacy',
        'websockets.protocol',
        'websockets.server',
        'websockets.sync',
        'websockets.typing',
        'websockets.uri',
        'websockets.utils',
        'websocket_client',
        'websocket',
        
        # Requests/HTTP
        'requests',
        'requests.adapters',
        'requests.auth',
        'requests.certs',
        'requests.compat',
        'requests.cookies',
        'requests.exceptions',
        'requests.hooks',
        'requests.models',
        'requests.packages',
        'requests.sessions',
        'requests.status_codes',
        'requests.structures',
        'requests.utils',
        'urllib3',
        'urllib3.connection',
        'urllib3.connectionpool',
        'urllib3.contrib',
        'urllib3.contrib.emscripten',
        'urllib3.contrib.emscripten.connection',
        'urllib3.contrib.emscripten.response',
        'urllib3.contrib.pyopenssl',
        'urllib3.exceptions',
        'urllib3.fields',
        'urllib3.filepost',
        'urllib3.packages',
        'urllib3.packages.six',
        'urllib3.poolmanager',
        'urllib3.response',
        'urllib3.util',
        'urllib3.util.connection',
        'urllib3.util.request',
        'urllib3.util.response',
        'urllib3.util.retry',
        'urllib3.util.ssl_',
        'urllib3.util.timeout',
        'urllib3.util.url',
        'urllib3.util.wait',
        'idna',
        'chardet',
        'certifi',
        
        # =========================================================================
        # SCREEN CAPTURE & MEDIA
        # =========================================================================
        'mss',
        'mss.base',
        'mss.darwin',
        'mss.exception',
        'mss.linux',
        'mss.models',
        'mss.screenshot',
        'mss.tools',
        'mss.windows',
        
        # Windows-specific screen capture
        'dxcam' if is_windows else '',
        
        # OpenCV
        'cv2',
        'cv2.cv2',
        'cv2.data',
        'cv2.load_config_py3',
        'cv2.misc',
        'cv2.version',
        
        # NumPy
        'numpy',
        'numpy._core',
        'numpy._core.multiarray',
        'numpy._core.umath',
        'numpy._core._multiarray_umath',
        'numpy._core.arrayprint',
        'numpy._core.fromnumeric',
        'numpy._core.function_base',
        'numpy._core.numeric',
        'numpy._core.numerictypes',
        'numpy._core.overrides',
        'numpy._core.records',
        'numpy._core.shape_base',
        'numpy._dtype_ctypes',
        'numpy._globals',
        'numpy._pytesttester',
        'numpy._utils',
        'numpy.compat',
        'numpy.compat.py3k',
        'numpy.fft',
        'numpy.lib',
        'numpy.lib.format',
        'numpy.lib.mixins',
        'numpy.lib.scimath',
        'numpy.lib.stride_tricks',
        'numpy.lib.utils',
        'numpy.linalg',
        'numpy.linalg.lapack_lite',
        'numpy.ma',
        'numpy.matrixlib',
        'numpy.polynomial',
        'numpy.random',
        'numpy.testing',
        'numpy.version',
        
        # PyGame
        'pygame',
        'pygame._freetype',
        'pygame.base',
        'pygame.bufferproxy',
        'pygame.color',
        'pygame.colordict',
        'pygame.cursors',
        'pygame.display',
        'pygame.draw',
        'pygame.event',
        'pygame.fastevent',
        'pygame.font',
        'pygame.gfxdraw',
        'pygame.image',
        'pygame.imageext',
        'pygame.joystick',
        'pygame.key',
        'pygame.mask',
        'pygame.math',
        'pygame.mixer',
        'pygame.mixer_music',
        'pygame.mouse',
        'pygame.overlay',
        'pygame.pixelarray',
        'pygame.pixelcopy',
        'pygame.rect',
        'pygame.rwobject',
        'pygame.scrap',
        'pygame.sndarray',
        'pygame.sprite',
        'pygame.surface',
        'pygame.surfarray',
        'pygame.sysfont',
        'pygame.time',
        'pygame.transform',
        'pygame.version',
        
        # =========================================================================
        # IMAGE PROCESSING
        # =========================================================================
        'PIL',
        'PIL.Image',
        'PIL.ImageChops',
        'PIL.ImageCms',
        'PIL.ImageColor',
        'PIL.ImageDraw',
        'PIL.ImageDraw2',
        'PIL.ImageEnhance',
        'PIL.ImageFile',
        'PIL.ImageFilter',
        'PIL.ImageFont',
        'PIL.ImageGrab',
        'PIL.ImageMath',
        'PIL.ImageMode',
        'PIL.ImageOps',
        'PIL.ImagePalette',
        'PIL.ImageQt',
        'PIL.ImageSequence',
        'PIL.ImageShow',
        'PIL.ImageStat',
        'PIL.ImageTk',
        'PIL.ImageWin',
        'PIL.ImageCrop',
        'PIL.BmpImagePlugin',
        'PIL.GifImagePlugin',
        'PIL.JpegImagePlugin',
        'PIL.PngImagePlugin',
        'PIL.TiffImagePlugin',
        'PIL.WebPImagePlugin',
        'PIL._imaging',
        'PIL._imagingcms',
        'PIL._imagingft',
        'PIL._imagingtk',
        
        'PyTurboJPEG',
        
        # =========================================================================
        # AUDIO PROCESSING
        # =========================================================================
        'speech_recognition',
        'speech_recognition.audio',
        'speech_recognition.exceptions',
        'speech_recognition.recognizers',
        
        # Platform-specific audio
        'pyaudio' if is_windows else '',
        'sounddevice' if not is_windows else '',
        
        # =========================================================================
        # INPUT CONTROL
        # =========================================================================
        'pynput',
        'pynput._util',
        'pynput.keyboard',
        'pynput.keyboard._base',
        'pynput.keyboard._win32' if is_windows else '',
        'pynput.keyboard._xorg' if is_linux else '',
        'pynput.keyboard._darwin' if is_macos else '',
        'pynput.mouse',
        'pynput.mouse._base',
        'pynput.mouse._win32' if is_windows else '',
        'pynput.mouse._xorg' if is_linux else '',
        'pynput.mouse._darwin' if is_macos else '',
        
        'keyboard',
        'keyboard._keyboard_event',
        'keyboard._nixkeyboard',
        'keyboard._winkeyboard',
        'keyboard._darwinkeyboard',
        'keyboard._generic',
        'keyboard._keyboard_tests',
        
        'pyautogui',
        'pyautogui._pyautogui_win' if is_windows else '',
        'pyautogui._pyautogui_x11' if is_linux else '',
        'pyautogui._pyautogui_osx' if is_macos else '',
        
        # =========================================================================
        # SYSTEM MONITORING
        # =========================================================================
        'psutil',
        'psutil._common',
        'psutil._compat',
        'psutil._psutil_windows' if is_windows else '',
        'psutil._psutil_linux' if is_linux else '',
        'psutil._psutil_posix' if not is_windows else '',
        'psutil._psutil_osx' if is_macos else '',
        
        'py_cpuinfo',
        'py_cpuinfo.cpuinfo',
        
        # Windows-specific
        'win32api' if is_windows else '',
        'win32con' if is_windows else '',
        'win32process' if is_windows else '',
        'win32security' if is_windows else '',
        'win32event' if is_windows else '',
        'win32clipboard' if is_windows else '',
        'win32com',
        'win32com.client',
        'pythoncom' if is_windows else '',
        'pywintypes' if is_windows else '',
        
        # =========================================================================
        # WEBRTC
        # =========================================================================
        'aiortc',
        'aiortc.mediastreams',
        'aiortc.rtcpeerconnection',
        'aiortc.rtcrtpparameters',
        'aiortc.rtcrtpsender',
        'aiortc.rtcrtpreceiver',
        'aiortc.rtcrtptransceiver',
        'aiortc.rtcstats',
        'aiortc.sdp',
        'aiortc.codecs',
        'aiortc.contrib',
        'aiortc.contrib.media',
        
        'av',
        'av.audio',
        'av.codec',
        'av.container',
        'av.datasets',
        'av.filter',
        'av.format',
        'av.library',
        'av.packet',
        'av.subtitle',
        'av.video',
        
        # =========================================================================
        # PERFORMANCE & COMPRESSION
        # =========================================================================
        'msgpack',
        'msgpack.fallback',
        
        'lz4',
        'lz4.block',
        'lz4.frame',
        'lz4.stream',
        'lz4.version',
        
        'zstandard',
        'zstandard.backend',
        'zstandard.backend_c',
        'zstandard.backend_cffi',
        
        'xxhash',
        
        # Platform-specific performance
        'uvloop' if not is_windows else '',
        'uvloop._noop' if is_windows else '',
        
        # =========================================================================
        # SECURITY
        # =========================================================================
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'cryptography.hazmat.backends.openssl.aead',
        'cryptography.hazmat.backends.openssl.backend',
        'cryptography.hazmat.backends.openssl.ciphers',
        'cryptography.hazmat.backends.openssl.cmac',
        'cryptography.hazmat.backends.openssl.decode_asn1',
        'cryptography.hazmat.backends.openssl.dh',
        'cryptography.hazmat.backends.openssl.dsa',
        'cryptography.hazmat.backends.openssl.ec',
        'cryptography.hazmat.backends.openssl.ed25519',
        'cryptography.hazmat.backends.openssl.ed448',
        'cryptography.hazmat.backends.openssl.encode_asn1',
        'cryptography.hazmat.backends.openssl.hashes',
        'cryptography.hazmat.backends.openssl.hmac',
        'cryptography.hazmat.backends.openssl.poly1305',
        'cryptography.hazmat.backends.openssl.rsa',
        'cryptography.hazmat.backends.openssl.x25519',
        'cryptography.hazmat.backends.openssl.x448',
        'cryptography.hazmat.backends.openssl.x509',
        'cryptography.hazmat.bindings',
        'cryptography.hazmat.bindings.openssl',
        'cryptography.hazmat.bindings.openssl.binding',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.asymmetric.dh',
        'cryptography.hazmat.primitives.asymmetric.dsa',
        'cryptography.hazmat.primitives.asymmetric.ec',
        'cryptography.hazmat.primitives.asymmetric.ed25519',
        'cryptography.hazmat.primitives.asymmetric.ed448',
        'cryptography.hazmat.primitives.asymmetric.padding',
        'cryptography.hazmat.primitives.asymmetric.rsa',
        'cryptography.hazmat.primitives.asymmetric.utils',
        'cryptography.hazmat.primitives.asymmetric.x25519',
        'cryptography.hazmat.primitives.asymmetric.x448',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.primitives.ciphers.algorithms',
        'cryptography.hazmat.primitives.ciphers.base',
        'cryptography.hazmat.primitives.ciphers.modes',
        'cryptography.hazmat.primitives.constant_time',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.hmac',
        'cryptography.hazmat.primitives.kdf',
        'cryptography.hazmat.primitives.keywrap',
        'cryptography.hazmat.primitives.padding',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.x509',
        
        # =========================================================================
        # ADDITIONAL UTILITIES
        # =========================================================================
        'pyotp',
        'qrcode',
        'qrcode.image',
        'qrcode.image.base',
        'qrcode.image.pil',
        'qrcode.image.svg',
        'qrcode.main',
        'qrcode.util',
        
        # Built-in modules that might be dynamically imported
        'email',
        'email.mime.text',
        'email.mime.multipart',
        'email.mime.base',
        'email.encoders',
        'email.utils',
        'email.header',
        'email.charset',
        'smtplib',
        'ssl',
        'hashlib',
        'hmac',
        'base64',
        'json',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'uuid',
        'logging',
        'logging.handlers',
        'queue',
        'threading',
        'multiprocessing',
        'multiprocessing.connection',
        'multiprocessing.context',
        'multiprocessing.dummy',
        'multiprocessing.managers',
        'multiprocessing.pool',
        'multiprocessing.process',
        'multiprocessing.queues',
        'multiprocessing.reduction',
        'multiprocessing.resource_tracker',
        'multiprocessing.shared_memory',
        'multiprocessing.sharedctypes',
        'multiprocessing.spawn',
        'multiprocessing.synchronize',
        'multiprocessing.util',
        'concurrent',
        'concurrent.futures',
        'subprocess',
        'tempfile',
        'shutil',
        'platform',
        'ctypes',
        'ctypes.wintypes' if is_windows else '',
        'ctypes.util',
        'signal',
        'select',
        'selectors',
        'socket',
        'time',
        'datetime',
        'calendar',
        'math',
        'random',
        'secrets',
        'statistics',
        'decimal',
        'fractions',
        'itertools',
        'functools',
        'collections',
        'collections.abc',
        'typing',
        'inspect',
        'warnings',
        'traceback',
        'sys',
        'os',
        'io',
        'pathlib',
        'stat',
        'glob',
        'fnmatch',
        'linecache',
        'locale',
        'gettext',
        'textwrap',
        'string',
        're',
        'difflib',
        'pprint',
        'reprlib',
        'enum',
        'types',
        'copy',
        'pickle',
        'shelve',
        'marshal',
        'dbm',
        'sqlite3',
        'zipfile',
        'tarfile',
        'csv',
        'configparser',
        'argparse',
        'optparse',
        'getopt',
        'readline',
        'rlcompleter',
        'code',
        'codeop',
        'py_compile',
        'compileall',
        'dis',
        'pickletools',
        'formatter',
        'html',
        'html.parser',
        'html.entities',
        'http',
        'http.client',
        'http.server',
        'http.cookies',
        'http.cookiejar',
        'webbrowser',
        'cgi',
        'cgitb',
        'wsgiref',
        'urllib',
        'urllib.parse',
        'urllib.request',
        'urllib.response',
        'urllib.error',
        'urllib.robotparser',
        'ftplib',
        'poplib',
        'imaplib',
        'nntplib',
        'smtpd',
        'telnetlib',
        'uuid',
        'socket',
        'ssl',
        'select',
        'selectors',
        'asyncore',
        'asynchat',
        'signal',
        'mmap',
        'errno',
        'ctypes',
        'threading',
        'multiprocessing',
        'concurrent',
        'subprocess',
        'sched',
        'queue',
        '_thread',
        '_dummy_thread',
        'dummy_threading',
        'contextvars',
        '_contextvars',
        'asyncio',
        
        # =========================================================================
        # C-EXTENSIONS (Platform-specific)
        # =========================================================================
        '_ctypes',
        '_socket',
        '_ssl',
        '_hashlib',
        '_random',
        '_datetime',
        '_pickle',
        '_elementtree' if hasattr(sys, 'getwindowsversion') else '',
        '_winreg' if is_windows else '',
        'winreg' if is_windows else '',
        
        # Cython
        'cython',
        'Cython',
        'Cython.Build',
        'Cython.Build.Dependencies',
        'Cython.Compiler',
        'Cython.Compiler.Analysis',
        'Cython.Compiler.Code',
        'Cython.Compiler.FlowControl',
        'Cython.Compiler.Lexicon',
        'Cython.Compiler.Main',
        'Cython.Compiler.MemoryView',
        'Cython.Compiler.Options',
        'Cython.Compiler.ParseTree',
        'Cython.Compiler.Parsing',
        'Cython.Compiler.Pipeline',
        'Cython.Compiler.Scanning',
        'Cython.Compiler.Visitor',
        'Cython.Runtime',
        'Cython.Tempita',
        'Cython.Utils',
        
        # =========================================================================
        # SETUPTOOLS & BUILD
        # =========================================================================
        'setuptools',
        'setuptools.command',
        'setuptools.command.build_ext',
        'setuptools.command.build_py',
        'setuptools.command.develop',
        'setuptools.command.egg_info',
        'setuptools.command.install',
        'setuptools.command.install_egg_info',
        'setuptools.command.install_lib',
        'setuptools.command.install_scripts',
        'setuptools.command.register',
        'setuptools.command.sdist',
        'setuptools.command.setopt',
        'setuptools.command.test',
        'setuptools.command.upload',
        'setuptools.dist',
        'setuptools.extension',
        'setuptools.glob',
        'setuptools.msvc',
        'setuptools.namespaces',
        'setuptools.package_index',
        'setuptools.sandbox',
        'setuptools.ssl_support',
        'setuptools.unicode_utils',
        'setuptools.version',
        'setuptools.wheel',
        'setuptools.windows_support',
        'pkg_resources',
        'pkg_resources.extern',
        'pkg_resources.extern.packaging',
        'pkg_resources._vendor',
        'pkg_resources._vendor.packaging',
        'pkg_resources._vendor.pyparsing',
        
        # =========================================================================
        # DYNAMIC IMPORTS (Common dynamic imports that PyInstaller misses)
        # =========================================================================
        'importlib',
        'importlib.util',
        'importlib.machinery',
        'importlib.abc',
        'importlib.metadata',
        'importlib.resources',
        'zipimport',
        
        # Additional modules that might be imported via __import__
        'colorsys',
        'colorsys',
        'colorsys',
        'colorsys',
        'colorsys',
        'colorsys',
        'colorsys',
        
        # =========================================================================
        # TESTING & DEBUGGING (if used)
        # =========================================================================
        'unittest',
        'unittest.mock',
        'unittest.util',
        'unittest.result',
        'unittest.loader',
        'unittest.runner',
        'unittest.suite',
        'unittest.async_case',
        'doctest',
        'pdb',
        'bdb',
        'cmd',
        'shlex',
        
        # =========================================================================
        # DATA FORMATS
        # =========================================================================
        'json',
        'csv',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'xml.parsers',
        'xml.parsers.expat',
        'xml.sax',
        'xml.sax.handler',
        'xml.sax.saxutils',
        'xml.sax.xmlreader',
        'xml.dom',
        'xml.dom.minidom',
        'xml.dom.pulldom',
        'xml.dom.NodeFilter',
        
        # =========================================================================
        # COMPRESSION & ARCHIVE
        # =========================================================================
        'gzip',
        'bz2',
        'lzma',
        'zipfile',
        'tarfile',
        'zlib',
        
        # =========================================================================
        # CRYPTO (Python standard library)
        # =========================================================================
        'hashlib',
        'hmac',
        'secrets',
        'base64',
        'binascii',
        
        # =========================================================================
        # OS-SPECIFIC
        # =========================================================================
        'msvcrt' if is_windows else '',
        'win32' if is_windows else '',
        'posix' if not is_windows else '',
        'pwd' if not is_windows else '',
        'grp' if not is_windows else '',
        'termios' if not is_windows else '',
        'tty' if not is_windows else '',
        'pty' if not is_windows else '',
        'fcntl' if not is_windows else '',
        'pipes' if not is_windows else '',
        'resource' if not is_windows else '',
        'nis' if not is_windows else '',
        'syslog' if not is_windows else '',
        
        # =========================================================================
        # OTHER
        # =========================================================================
        'array',
        'audioop',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
        'cmath',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude unnecessary packages to reduce size
        'tkinter',
        'tcl',
        'tk',
        '_tkinter',
        'turtle',
        'matplotlib',
        'scipy',
        'pandas',
        'scikit-learn',
        'tensorflow',
        'torch',
        'keras',
        'plotly',
        'bokeh',
        'dash',
        'flask_admin',
        'flask_restful',
        'sqlalchemy',
        'django',
        'cherrypy',
        'bottle',
        'pyramid',
        'tornado',
        'twisted',
        'zmq',
        'ipython',
        'jupyter',
        'notebook',
        'spyder',
        'pyqt5',
        'pyside2',
        'wx',
        'kivy',
        'pygame_menu',
        'pyglet',
        'cocos2d',
        'panda3d',
        'ogre',
        'pyopengl',
        'pygobject',
        'gtk',
        'qtpy',
        'enaml',
        'traits',
        'traitsui',
        'mayavi',
        'vtk',
        'opencv_contrib_python',
        'opencv_python_headless',
        'simpleaudio',
        'soundfile',
        'audioread',
        'pydub',
        'librosa',
        'pysoundfile',
        'pyaudio',
        'sounddevice',
        'soundcard',
        'python_speech_features',
        'deap',
        'gym',
        'stable_baselines',
        'ray',
        'rllib',
        'mujoco_py',
        'pybullet',
        'roboschool',
        'gymnasium',
        'gym.envs',
        'gym.wrappers',
        'gym.spaces',
        'gym.utils',
        'gym.logger',
        'gym.vector',
        'gym.error',
        'gym.version',
        'pygame._sdl2',
        'pygame._sdl2.audio',
        'pygame._sdl2.controller',
        'pygame._sdl2.event',
        'pygame._sdl2.joystick',
        'pygame._sdl2.keyboard',
        'pygame._sdl2.mouse',
        'pygame._sdl2.render',
        'pygame._sdl2.rwops',
        'pygame._sdl2.sensor',
        'pygame._sdl2.touch',
        'pygame._sdl2.video',
        'pygame.cdrom',
        'pygame.constants',
        'pygame.controller',
        'pygame.examples',
        'pygame.freetype',
        'pygame.gfxdraw',
        'pygame.joystick',
        'pygame.midi',
        'pygame.pixelarray',
        'pygame.sndarray',
        'pygame.surfarray',
        'pygame.tests',
        'pygame.threshold',
        'pygame._sdl2.audio',
        'pygame._sdl2.controller',
        'pygame._sdl2.event',
        'pygame._sdl2.joystick',
        'pygame._sdl2.keyboard',
        'pygame._sdl2.mouse',
        'pygame._sdl2.render',
        'pygame._sdl2.rwops',
        'pygame._sdl2.sensor',
        'pygame._sdl2.touch',
        'pygame._sdl2.video',
        'test',
        'tests',
        'unittest',
        'pytest',
        'nose',
        'coverage',
        'tox',
        'virtualenv',
        'pip',
        'wheel',
        'setuptools',
        'easy_install',
        'distutils',
        'ensurepip',
        'venv',
        'py_compile',
        'compileall',
        'zipapp',
        'zipimport',
        'modulefinder',
        'runpy',
        'pkgutil',
        'site',
        'sitecustomize',
        'usercustomize',
        'distutils',
        'ensurepip',
        'venv',
        'py_compile',
        'compileall',
        'zipapp',
        'zipimport',
        'modulefinder',
        'runpy',
        'pkgutil',
        'site',
        'sitecustomize',
        'usercustomize',
    ],
    noarchive=False,
    optimize=0,
    upx=False,  # UPX compression can cause issues with some DLLs
)

# =============================================================================
# COLLECT BINARIES AND DATA FILES
# =============================================================================

# Platform-specific binaries
if is_windows:
    # Windows DLLs that might be needed
    a.binaries += [
        # Add any required Windows DLLs here
        # Example: ('C:\\Windows\\System32\\some.dll', '.'),
    ]

# Data files (config files, images, etc.)
a.datas += [
    # Add any data files your app needs
    # Example: ('config.ini', 'config.ini', 'DATA'),
]

# =============================================================================
# CREATE PYZ
# =============================================================================

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

# =============================================================================
# CREATE EXECUTABLE
# =============================================================================

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='client',  # Output executable name
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,  # Enable UPX compression (can reduce size by 30-50%)
    console=True,  # Set to False for windowless application
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # Add icon path if you have one: 'icon.ico'
    version=None,  # Add version file if you have one
    manifest=None,
    uac_admin=False,
    uac_uiaccess=False,
    rt_manifest=None,
    aslr=False,
    dpiaware=False,
    sidebyside=False,
    binding_redirects=False,
    com_server=False,
    com_library=False,
    com_typelib=False,
    com_embedding=False,
    com_typelib_embedding=False,
    com_server_embedding=False,
    com_library_embedding=False,
    com_typelib_library=False,
    com_server_library=False,
    com_typelib_server=False,
    com_typelib_library_embedding=False,
    com_server_library_embedding=False,
    com_typelib_server_embedding=False,
)

# =============================================================================
# COLLECT FOR ONE-FILE MODE
# =============================================================================

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='client'  # Folder name for one-folder mode
)