param()
$ErrorActionPreference = "SilentlyContinue"
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs; exit }
function RemoveRegValue([string]$path,[string]$name){ if (Test-Path $path) { try { Remove-ItemProperty -Path $path -Name $name -ErrorAction SilentlyContinue } catch {} } }
function RemoveRegKey([string]$path){ if (Test-Path $path) { try { Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue } catch {} } }
function SetRegDword([string]$path,[string]$name,[int]$value){ New-Item -Path $path -Force | Out-Null; New-ItemProperty -Path $path -Name $name -PropertyType DWord -Value $value -Force | Out-Null }
function DelFile([string]$path){ if (Test-Path $path) { try { Remove-Item -Path $path -Force -ErrorAction SilentlyContinue } catch {} } }
function DelDir([string]$path){ if (Test-Path $path) { try { Remove-Item -Path $path -Recurse -Force -ErrorAction SilentlyContinue } catch {} } }
function DeleteTask([string]$name){ try { schtasks.exe /delete /tn $name /f | Out-Null } catch {} }
function StopDeleteService([string]$name){ try { sc.exe stop $name | Out-Null } catch {}; try { sc.exe delete $name | Out-Null } catch {} }
function TaskKillName([string]$name){ try { taskkill.exe /F /IM $name | Out-Null } catch {} }
Write-Host ""
Write-Host "==============================================================================="
Write-Host "         CLIENT.PY COMPLETE SYSTEM RESTORE SCRIPT v2.0 (PowerShell)"
Write-Host "==============================================================================="
Write-Host ""
Write-Host "This will remove ALL traces of client.py from your system including:"
Write-Host "  - Registry keys (HKCU and HKLM)"
Write-Host "  - Scheduled tasks"
Write-Host "  - Startup entries"
Write-Host "  - Services"
Write-Host "  - Files and directories"
Write-Host "  - Windows Defender modifications"
Write-Host "  - Notification settings"
Write-Host "  - UAC bypass registry hijacks"
Write-Host "  - COM handler hijacks"
Write-Host "  - Environment variable hijacks"
Write-Host ""
Write-Host "Press CTRL+C to cancel, or"
Read-Host
Write-Host ""
Write-Host "[STEP 1/12] Removing Registry Run Keys..."
Write-Host "==============================================================================="
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" "svchost32"
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" "WindowsSecurityUpdate"
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce" "svchost32"
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\RunOnce" "WindowsSecurityUpdate"
Write-Host "[OK] Registry Run keys removed"
Write-Host ""
Write-Host "[STEP 2/12] Removing UAC Bypass Registry Keys (fodhelper/computerdefaults)..."
Write-Host "==============================================================================="
RemoveRegKey "HKCU:\Software\Classes\ms-settings\Shell\Open\command"
RemoveRegKey "HKCU:\Software\Classes\ms-settings\Shell\Open"
RemoveRegKey "HKCU:\Software\Classes\ms-settings\Shell"
RemoveRegKey "HKCU:\Software\Classes\ms-settings"
Write-Host "[OK] ms-settings protocol hijack removed"
Write-Host ""
Write-Host "[STEP 3/12] Removing EventVwr UAC Bypass Registry Keys..."
Write-Host "==============================================================================="
RemoveRegKey "HKCU:\Software\Classes\mscfile\shell\open\command"
RemoveRegKey "HKCU:\Software\Classes\mscfile\shell\open"
RemoveRegKey "HKCU:\Software\Classes\mscfile\shell"
RemoveRegKey "HKCU:\Software\Classes\mscfile"
Write-Host "[OK] EventVwr bypass registry keys removed"
Write-Host ""
Write-Host "[STEP 4/12] Removing SDCLT UAC Bypass Registry Keys..."
Write-Host "==============================================================================="
RemoveRegKey "HKCU:\Software\Classes\exefile\shell\open\command"
RemoveRegKey "HKCU:\Software\Classes\exefile\shell\open"
RemoveRegKey "HKCU:\Software\Classes\Folder\shell\open\command"
RemoveRegKey "HKCU:\Software\Classes\Folder\shell\open"
Write-Host "[OK] SDCLT bypass registry keys removed"
Write-Host ""
Write-Host "[STEP 5/12] Removing Additional UAC Bypass Registry Keys..."
Write-Host "==============================================================================="
RemoveRegKey "HKCU:\Software\Classes\AppX82a6gwre4fdg3bt635tn5ctqjf8msdd2\Shell\open\command"
RemoveRegKey "HKCU:\Software\Classes\AppX82a6gwre4fdg3bt635tn5ctqjf8msdd2\Shell\open"
RemoveRegKey "HKCU:\Software\Classes\AppX82a6gwre4fdg3bt635tn5ctqjf8msdd2\Shell"
RemoveRegKey "HKCU:\Software\Classes\AppX82a6gwre4fdg3bt635tn5ctqjf8msdd2"
RemoveRegKey "HKCU:\Software\Classes\.exe\shell\open\command"
Write-Host "[OK] Additional UAC bypass keys removed"
Write-Host ""
Write-Host "[STEP 6/12] Removing COM Handler Hijacks..."
Write-Host "==============================================================================="
RemoveRegKey "HKCU:\Software\Classes\CLSID\{3E5FC7F9-9A51-4367-9063-A120244FBEC7}\InprocServer32"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{3E5FC7F9-9A51-4367-9063-A120244FBEC7}"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{D2E7041B-2927-42FB-8E9F-7CE93B6DC937}\InprocServer32"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{D2E7041B-2927-42FB-8E9F-7CE93B6DC937}"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{BCDE0395-E52F-467C-8E3D-C4579291692E}\InprocServer32"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{BCDE0395-E52F-467C-8E3D-C4579291692E}"
Write-Host "[OK] COM handler hijacks removed"
Write-Host ""
Write-Host "[STEP 7/12] Removing Environment Variable Hijacks..."
Write-Host "==============================================================================="
RemoveRegValue "HKCU:\Volatile Environment" "windir"
RemoveRegValue "HKCU:\Environment" "windir"
RemoveRegValue "HKCU:\Environment" "PATH_MODIFIED_BY_AGENT"
Write-Host "[OK] Environment variable hijacks removed"
Write-Host ""
Write-Host "[STEP 8/12] Restoring Notification Settings..."
Write-Host "==============================================================================="
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications" "ToastEnabled"
RemoveRegValue "HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer" "DisableNotificationCenter"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer" "DisableNotificationCenter"
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows Defender\UX Configuration" "Notification_Suppress"
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" "NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK"
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" "NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK"
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.WindowsUpdate" "Enabled"
RemoveRegValue "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance" "Enabled"
RemoveRegValue "HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications" "NoToastApplicationNotification"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Notifications" "DisableNotifications"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Systray" "HideSystray"
Write-Host "[OK] Notification settings restored"
Write-Host ""
Write-Host "[STEP 9/12] Removing Context Menu Admin Shortcuts..."
Write-Host "==============================================================================="
RemoveRegKey "HKCR:\Directory\Background\shell\runas\command"
RemoveRegKey "HKCR:\Directory\Background\shell\runas"
RemoveRegKey "HKCR:\Directory\Background\shell\PowershellAdmin\command"
RemoveRegKey "HKCR:\Directory\Background\shell\PowershellAdmin"
Write-Host "[OK] Context menu admin shortcuts removed"
Write-Host ""
Write-Host "[STEP 9/12] Removing Scheduled Tasks..."
Write-Host "==============================================================================="
DeleteTask "WindowsSecurityUpdate"
DeleteTask "WindowsSecurityUpdateTask"
DeleteTask "MicrosoftEdgeUpdateTaskUser"
DeleteTask "SystemUpdateTask"
schtasks.exe /query /tn "\Microsoft\Windows\DiskCleanup\SilentCleanup" | Out-Null
if ($LASTEXITCODE -eq 0) { Write-Host "[INFO] SilentCleanup task exists - verify it's legitimate in Task Scheduler" }
Write-Host "[OK] Scheduled tasks removed"
Write-Host ""
Write-Host "[STEP 10/12] Removing Windows Services..."
Write-Host "==============================================================================="
StopDeleteService "WindowsSecurityService"
StopDeleteService "WindowsSecurityUpdate"
StopDeleteService "SystemUpdateService"
try { sc.exe config WinDefend start= auto | Out-Null } catch {}
try { sc.exe start WinDefend | Out-Null } catch {}
try { sc.exe config SecurityHealthService start= auto | Out-Null } catch {}
try { sc.exe start SecurityHealthService | Out-Null } catch {}
Write-Host "[OK] Windows services removed"
Write-Host ""
Write-Host "[STEP 11/12] Removing Startup Folder Entries and Files..."
Write-Host "==============================================================================="
DelFile "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\SystemService.bat"
DelFile "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\svchost32.bat"
DelFile "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\WindowsUpdate.bat"
DelFile "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\svchost32.exe"
DelFile "$env:LOCALAPPDATA\Microsoft\Windows\svchost32.exe"
DelFile "$env:LOCALAPPDATA\Microsoft\Windows\svchost32.bat"
DelFile "$env:LOCALAPPDATA\Microsoft\Windows\svchost32.py"
DelFile "$env:APPDATA\Microsoft\Windows\svchost32.exe"
DelFile "$env:APPDATA\Microsoft\Windows\svchost32.bat"
DelFile "$env:APPDATA\Microsoft\Windows\svchost32.py"
DelFile "$env:TEMP\svchost32.py"
DelFile "$env:TEMP\svchost32.bat"
DelFile "$env:TEMP\svchost32.exe"
DelFile "$env:TEMP\watchdog.py"
DelFile "$env:TEMP\watchdog.bat"
DelFile "$env:TEMP\deploy.ps1"
DelFile "$env:TEMP\tamper_protection.py"
DelFile "$env:TEMP\tamper_protection.exe"
DelFile "$env:TEMP\uac_bypass.reg"
DelDir "$env:TEMP\Windows"
DelDir "$env:TEMP\System32"
DelDir "$env:TEMP\junction_target"
DelDir "$env:TEMP\fake_system32"
DelFile "$env:TEMP\profiler.dll"
DelFile "$env:TEMP\DismCore.dll"
DelFile "$env:TEMP\wow64log.dll"
DelDir "$env:TEMP\mock_system32"
DelFile "$env:TEMP\fake.msc"
DelFile "C:\Windows\System32\svchost32.exe"
DelFile "C:\Windows\SysWOW64\svchost32.exe"
DelFile "C:\Windows\System32\drivers\svchost32.exe"
Write-Host "[OK] Startup entries and files removed"
Write-Host ""
Write-Host "[STEP 12/12] Restoring Windows Defender Settings..."
Write-Host "==============================================================================="
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" "DisableAntiSpyware"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" "DisableRealtimeMonitoring"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" "DisableBehaviorMonitoring"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" "DisableOnAccessProtection"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" "DisableScanOnRealtimeEnable"
RemoveRegValue "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" "DisableIOAVProtection"
try { Set-MpPreference -DisableRealtimeMonitoring $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableBehaviorMonitoring $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableIOAVProtection $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableOnAccessProtection $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableIntrusionPreventionSystem $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableScriptScanning $false -ErrorAction SilentlyContinue } catch {}
try { Set-MpPreference -DisableTamperProtection $false -ErrorAction SilentlyContinue } catch {}
try { Remove-MpPreference -ExclusionPath "$env:TEMP" -ErrorAction SilentlyContinue } catch {}
try { Remove-MpPreference -ExclusionPath "C:\Windows\Temp" -ErrorAction SilentlyContinue } catch {}
try { Remove-MpPreference -ExclusionPath "C:\Users\Public" -ErrorAction SilentlyContinue } catch {}
try { Remove-MpPreference -ExclusionPath "C:\ProgramData" -ErrorAction SilentlyContinue } catch {}
SetRegDword "HKLM:\SOFTWARE\Microsoft\Windows Defender\Features" "TamperProtection" 1
SetRegDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Features" "TamperProtection" 1
Write-Host "[OK] Windows Defender settings restored"
Write-Host ""
Write-Host "==============================================================================="
Write-Host "[ADDITIONAL CLEANUP] Stopping Running Processes and Final Cleanup..."
Write-Host "==============================================================================="
TaskKillName "svchost32.exe"
TaskKillName "client.py"
TaskKillName "pythonw.exe"
Write-Host "[CRITICAL] Re-enabling Task Manager..."
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System" "DisableTaskMgr"
SetRegDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System" "DisableTaskMgr" 0
Write-Host "[CRITICAL] Re-enabling Registry Editor..."
RemoveRegValue "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System" "DisableRegistryTools"
SetRegDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System" "DisableRegistryTools" 0
Write-Host "[CRITICAL] Re-enabling Command Prompt..."
RemoveRegValue "HKCU:\Software\Policies\Microsoft\Windows\System" "DisableCMD"
SetRegDword "HKCU:\Software\Policies\Microsoft\Windows\System" "DisableCMD" 0
Write-Host "[CRITICAL] Restoring PowerShell Execution Policy..."
RemoveRegValue "HKCU:\Software\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell" "ExecutionPolicy"
SetRegDword "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "EnableLUA" 1
SetRegDword "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "ConsentPromptBehaviorAdmin" 5
SetRegDword "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "PromptOnSecureDesktop" 1
RemoveRegValue "HKCU:\Environment" "COR_ENABLE_PROFILING"
RemoveRegValue "HKCU:\Environment" "COR_PROFILER"
RemoveRegValue "HKCU:\Environment" "COR_PROFILER_PATH"
SetRegDword "HKLM:\SYSTEM\CurrentControlSet\Services\WdFilter" "Start" 0
try { Get-NetFirewallRule -DisplayName "Python Agent*" -ErrorAction SilentlyContinue | Remove-NetFirewallRule -ErrorAction SilentlyContinue } catch {}
try {
    $ns = "root\subscription"
    Get-WmiObject -Namespace $ns -Class __EventFilter -Filter "Name='WindowsSecurityFilter'" | Remove-WmiObject -ErrorAction SilentlyContinue
    Get-WmiObject -Namespace $ns -Class CommandLineEventConsumer -Filter "Name='WindowsSecurityConsumer'" | Remove-WmiObject -ErrorAction SilentlyContinue
    Get-WmiObject -Namespace $ns -Class __FilterToConsumerBinding | Where-Object { $_.Filter -match "WindowsSecurityFilter" -or $_.Consumer -match "WindowsSecurityConsumer" } | Remove-WmiObject -ErrorAction SilentlyContinue
} catch {}
RemoveRegKey "HKCU:\Software\Classes\CLSID\{00021401-0000-0000-C000-000000000046}\InProcServer32"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{13709620-C279-11CE-A49E-444553540000}\InProcServer32"
RemoveRegKey "HKCU:\Software\Classes\CLSID\{9BA05972-F6A8-11CF-A442-00A0C90A8F39}\InProcServer32"
Write-Host "[OK] Additional cleanup completed"
Write-Host ""
Write-Host "==============================================================================="
Write-Host "[MALWAREBYTES REPORT] Removing detected artifacts (full coverage)..."
Write-Host "==============================================================================="
StopDeleteService "P2PEnhance"
RemoveRegKey "HKLM:\SYSTEM\CurrentControlSet\Services\P2PEnhance"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\P2PEnhance"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{C845414C-903C-4218-9DE7-132AB97FDF62}"
RemoveRegValue "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{C845414C-903C-4218-9DE7-132AB97FDF62}" "InstallSource"
RemoveRegKey "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe"
Get-ChildItem HKU:\ | Where-Object { $_.PSChildName -match '^S-1-5-21-' } | ForEach-Object {
    $runPath = "HKU:\{0}\Software\Microsoft\Windows\CurrentVersion\Run" -f $_.PSChildName
    $runOncePath = "HKU:\{0}\Software\Microsoft\Windows\CurrentVersion\RunOnce" -f $_.PSChildName
    RemoveRegValue $runPath "svchost32"
    RemoveRegValue $runOncePath "svchost32"
}
DelDir "C:\ProgramData\QuteClient"
DelDir "C:\ProgramData\QuteClient\install"
DelDir "C:\ProgramData\QuteClient\test"
DelDir "C:\Program Files (x86)\AW Manager"
DelDir "C:\Program Files (x86)\AW Manager\Windows Manager"
DelDir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\P2PEnhance"
DelFile "C:\Program Files (x86)\P2PEnhance\P2PEnhance.exe"
DelFile "C:\ProgramData\QuteClient\install\fw-enable.vbs"
DelFile "C:\ProgramData\QuteClient\install\runme.bat"
DelFile "C:\ProgramData\QuteClient\install\runme_end.bat"
DelFile "C:\ProgramData\QuteClient\install\sc-create.bat"
DelFile "C:\ProgramData\QuteClient\test\quteclient.ini"
DelFile "C:\ProgramData\QuteClient\test\torrent.hash"
DelFile "C:\ProgramData\QuteClient\test\torrent.ini"
DelFile "C:\ProgramData\QuteClient\test\updated_quteclient.ini"
DelFile "C:\ProgramData\QuteClient\test\updated_torrent.hash"
DelFile "C:\ProgramData\QuteClient\test\updated_torrent.ini"
DelFile "C:\ProgramData\QuteClient\qplugins.dll"
DelFile "C:\Program Files (x86)\AW Manager\Windows Manager\Windows Updater.ini"
DelFile "C:\Program Files (x86)\AW Manager\Windows Manager\Uninstall.lnk"
DelFile "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\P2PEnhance\P2PEnhance Website.lnk"
DelFile "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\P2PEnhance\Claim money.lnk"
DelFile "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\P2PEnhance\Uninstall.lnk"
Get-ChildItem "C:\Users" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $lp = Join-Path $_.FullName "AppData\Local\Microsoft\Windows\svchost.exe"
    $rp = Join-Path $_.FullName "AppData\Roaming\Microsoft\Windows\svchost.exe"
    DelFile $lp
    DelFile $rp
}
DelFile "C:\Users\Brylle\AppData\Local\Microsoft\Windows\svchost.exe"
DelFile "C:\$Recycle.Bin\S-1-5-21-965317178-1596221690-3401380953-1000\$R20RYTF\CROSSFIRE HACK  ESP NO RECOIL  MORE.EXE"
DelFile "C:\$Recycle.Bin\S-1-5-21-965317178-1596221690-3401380953-1000\$R33PYFN.EXE"
DelFile "C:\$Recycle.Bin\S-1-5-21-965317178-1596221690-3401380953-1000\$RISE28A.EXE"
DelFile "C:\Users\Brylle\FREE IMGUI MENU-BRYLLE\FREE IMGUI MENU FROM-BRYLLE\EXAMPLES\EXAMPLE_WIN32_DIRECTX11\RELEASE\EXAMPLE_WIN32_DIRECTX11.EXE"
DelFile "C:\Users\Brylle\KDU-1.4.4\SOURCE\HAMAKAZE\OUTPUT\X64\RELEASE\KDU.EXE"
try { Clear-RecycleBin -Force -ErrorAction SilentlyContinue } catch {}
Write-Host "[OK] Malwarebytes-detected artifacts removed"
Write-Host ""
Write-Host "==============================================================================="
Write-Host "[MALWAREBYTES REPORT] Removing detected PUP/Threat artifacts..."
Write-Host "==============================================================================="
StopDeleteService "P2PEnhance"
RemoveRegKey "HKLM:\SYSTEM\CurrentControlSet\Services\P2PEnhance"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\P2PEnhance"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{C845414C-903C-4218-9DE7-132AB97FDF62}"
RemoveRegKey "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe"
RemoveRegKey "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe"
Get-ChildItem HKU:\ | Where-Object { $_.PSChildName -match '^S-1-5-21-' } | ForEach-Object {
    $runPath = "HKU:\{0}\Software\Microsoft\Windows\CurrentVersion\Run" -f $_.PSChildName
    $runOncePath = "HKU:\{0}\Software\Microsoft\Windows\CurrentVersion\RunOnce" -f $_.PSChildName
    RemoveRegValue $runPath "svchost32"
    RemoveRegValue $runOncePath "svchost32"
}
DelDir "C:\ProgramData\QuteClient"
DelDir "C:\Program Files (x86)\AW Manager"
DelDir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\P2PEnhance"
DelDir "C:\Program Files (x86)\P2PEnhance"
DelFile "$env:LOCALAPPDATA\Microsoft\Windows\svchost.exe"
DelFile "$env:APPDATA\Microsoft\Windows\svchost.exe"
try { Clear-RecycleBin -Force -ErrorAction SilentlyContinue } catch {}
Write-Host "[OK] Malwarebytes-detected artifacts removed"
Write-Host ""
Write-Host "==============================================================================="
Write-Host "                        CLEANUP COMPLETE"
Write-Host "==============================================================================="
Write-Host ""
Write-Host "All traces of client.py have been removed from your system."
Write-Host ""
Write-Host "RECOMMENDED NEXT STEPS:"
Write-Host "  1. RESTART YOUR COMPUTER for changes to take full effect"
Write-Host "  2. Run Windows Defender full scan: Start > Windows Security > Virus & threat protection > Full scan"
Write-Host "  3. Check Task Manager (Ctrl+Shift+Esc) for any suspicious processes"
Write-Host "  4. Verify Task Scheduler: taskschd.msc (ensure no suspicious scheduled tasks)"
Write-Host "  5. Check Services: services.msc (ensure no suspicious services)"
Write-Host "  6. Verify startup items: msconfig > Startup tab"
Write-Host "  7. Verify notification settings: Start > Settings > System > Notifications"
Write-Host "  8. Check registry: regedit (verify HKCU\Software\Microsoft\Windows\CurrentVersion\Run)"
Write-Host ""
Write-Host "REGISTRY AREAS CLEANED:"
Write-Host "  - HKCU\Software\Microsoft\Windows\CurrentVersion\Run"
Write-Host "  - HKCU\Software\Microsoft\Windows\CurrentVersion\RunOnce"
Write-Host "  - HKCU\Software\Classes\ms-settings"
Write-Host "  - HKCU\Software\Classes\mscfile"
Write-Host "  - HKCU\Software\Classes\exefile"
Write-Host "  - HKCU\Software\Classes\Folder"
Write-Host "  - HKCU\Software\Classes\CLSID (COM hijacks)"
Write-Host "  - HKCU\Volatile Environment"
Write-Host "  - HKLM\SOFTWARE\Policies\Microsoft\Windows Defender"
Write-Host "  - Notification settings (HKCU + HKLM)"
Write-Host ""
Write-Host "FILES AND FOLDERS CLEANED:"
Write-Host "  - $env:LOCALAPPDATA\Microsoft\Windows\svchost32.*"
Write-Host "  - $env:APPDATA\Microsoft\Windows\svchost32.*"
Write-Host "  - $env:TEMP\svchost32.*"
Write-Host "  - $env:TEMP\Windows (fake directory)"
Write-Host "  - $env:TEMP\System32 (fake directory)"
Write-Host "  - All watchdog and tamper protection files"
Write-Host "  - All temporary exploit files (DLLs, REG files, etc.)"
Write-Host ""
Write-Host "SCHEDULED TASKS REMOVED:"
Write-Host "  - WindowsSecurityUpdate"
Write-Host "  - WindowsSecurityUpdateTask"
Write-Host "  - MicrosoftEdgeUpdateTaskUser"
Write-Host "  - SystemUpdateTask"
Write-Host ""
Write-Host "SERVICES REMOVED:"
Write-Host "  - WindowsSecurityService"
Write-Host "  - WindowsSecurityUpdate"
Write-Host "  - SystemUpdateService"
Write-Host ""
Write-Host "Your system should now be restored to its original state."
Write-Host "If you notice any remaining issues, please run test_restore.bat to verify cleanup."
Write-Host ""
Read-Host
exit 0
